language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
install:
  - pip install .
script: 
  - cd tests; py.test
deploy:
    provider: pypi
    user: extended_pathlib
    on:
        tags: true


